# Perform CI on ARM MacOS (M1+) using github
name: macos-ci
on: push
jobs:
    build_and_test:
        runs-on: macos-latest
        steps:
            - run: brew install fgindraud/bio/kissplice
            - run: brew audit --strict --new --online kissplice
            - run: brew test kissplice
#            - run: git clone https://gitlab.inria.fr/erable/kissplice.git
#            - run: cmake -S kissplice -B build -DUSE_BUNDLED_BCALM=ON -DCMAKE_INSTALL_PREFIX=prefix
#            - run: cmake --build build -j3
#            - run: cmake --install build
#            - run: cd build && ctest --output-on-failure
#            - name: Retrieve test result files
#              if: failure()
#              uses: actions/upload-artifact@v4
#              with:
#                name: test-result-files
#                path: kissplice/tests/
