# Perform CI on ARM MacOS (M1+) using github
name: macos-ci
on: push
jobs:
    build_and_test:
        runs-on: macos-latest
        steps:
            - run: git clone https://gitlab.inria.fr/erable/kissplice.git
            - run: cmake -S kissplice -B build
            - run: cmake --build build
            - run: cmake --install build
            - run: cd build && make test
