# Perform CI on ARM MacOS (M1+) using github
name: macos-ci
on: push
jobs:
    build_and_test:
        runs-on: macos-latest
        steps:
            - run: git clone --recursive https://github.com/GATB/bcalm
            - run: cmake -S bcalm -B build
            - run: cmake --build build
            - run: ls build/
            - run: false # stop there until bcalm fixed
            - run: brew install fgindraud/bio/bcalm
            - run: git clone https://gitlab.inria.fr/erable/kissplice.git
            - run: cmake -S kissplice -B build -DCMAKE_INSTALL_PREFIX=prefix
            - run: cmake --build build -j3
            - run: cmake --install build
            - run: cd build && make test
